spring.application.name=Catalogo_Jogos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_catalogo_jogos
spring.datasource.username=postgres
spring.datasource.password=Lucena08
spring.jpa.hibernate.ddl-auto=update
server.port=8081
usuario.url=localhost:8080